In [14]:
import numpy as np
x = np.random.randint(1, 20, (4, 5))
print(x)

[[19 12 16 18  9]
 [ 6  5 17  4 17]
 [18 18 12  4 14]
 [ 3 10 12  1 18]]


In [15]:
x = x[x[:, 0].argsort()]
print(x)

[[ 3 10 12  1 18]
 [ 6  5 17  4 17]
 [18 18 12  4 14]
 [19 12 16 18  9]]
