In [151]:
import numpy as np
li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [152]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [153]:
print(li[2])
print(arr[2])
print(li[:3])
print(arr[:3])

3
3
[1, 2, 3]
[1 2 3]


In [154]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [155]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [156]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])

10
10
10


In [157]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [158]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [159]:
print(li_2d[0:3][0])

[1, 2, 3, 4]


In [160]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [161]:
print(li_2d[2:4][1:3])
print(arr_2d[2:4, 1:3])

[[13, 14, 15, 16]]
[[10 11]
 [14 15]]
