In [155]:
import numpy as np
li = [1, 2, 3, 4, 5, 6]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5, 6]
[16  8  2  4 19]
[ 9 18  7 18 10]


In [156]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6, 7]

In [157]:
c = a + b
c

array([25, 26,  9, 22, 29])

In [158]:
d = a - b
d

array([  7, -10,  -5, -14,   9])

In [159]:
e = a * b
e

array([144, 144,  14,  72, 190])

In [160]:
f = a / b
f

array([1.77777778, 0.44444444, 0.28571429, 0.22222222, 1.9       ])

In [161]:
g = a ** b
g

array([          0,           0,         128,           0, -2147040887],
      dtype=int32)

In [162]:
h = a // b
h

array([1, 0, 0, 0, 1], dtype=int32)

In [163]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[16  8  2  4 19]
49
9.8
2
2
19
4


In [164]:
print(a)
print(b)

[16  8  2  4 19]
[ 9 18  7 18 10]


In [165]:
a > b

array([ True, False, False, False,  True])

In [166]:
a < b

array([False,  True,  True,  True, False])

In [167]:
a == b

array([False, False, False, False, False])

In [168]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [169]:
a[1] = 0
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True False  True  True  True]


In [170]:
print(np.logical_not(a))

[False  True False False False]
