In [220]:
import numpy as np

In [221]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [222]:
b = np.zeros([3, 3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [223]:
b = np.full((3, 3), 5, dtype=float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [224]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [227]:
b = np.linspace(2, 10, 5, dtype = int)
b

array([ 2,  4,  6,  8, 10])

In [228]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

In [229]:
b = np.linspace(2, 10, 7, dtype = int)
b

array([ 2,  3,  4,  6,  7,  8, 10])

In [230]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [231]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [232]:
b = np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [233]:
b = np.random.rand(4)
b

array([0.98129946, 0.56580515, 0.81539503, 0.52236683])

In [234]:
b = np.random.rand(3, 4)
b

array([[0.40113129, 0.49888899, 0.06856909, 0.89972573],
       [0.37295848, 0.28435523, 0.15262062, 0.52432025],
       [0.64733143, 0.37638546, 0.35998633, 0.80825137]])